"""empty message

Revision ID: 251276031b2e
Revises: c18cae59d3cf
Create Date: 2023-02-27 17:36:24.845604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251276031b2e'
down_revision = 'c18cae59d3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.String(length=128),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.String(length=128),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
