"""empty message

Revision ID: 6594be44fddb
Revises: 9e80796794e3
Create Date: 2023-03-01 13:40:22.585326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6594be44fddb'
down_revision = '9e80796794e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_doctor_password_hash'), ['password_hash'], unique=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.create_index(batch_op.f('ix_patient_password_hash'), ['password_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_password_hash'))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_password_hash'))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
