"""empty message

Revision ID: 9e80796794e3
Revises: 251276031b2e
Create Date: 2023-02-28 18:10:24.051039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e80796794e3'
down_revision = '251276031b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.drop_column('pdf')

    # ### end Alembic commands ###
