"""empty message

Revision ID: c18cae59d3cf
Revises: e7913157240e
Create Date: 2023-02-27 17:11:05.903030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18cae59d3cf'
down_revision = 'e7913157240e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('consultation_schedule_office',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('consultation_schedule_away',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_series', sa.String(length=8), nullable=False))
        batch_op.add_column(sa.Column('id_number', sa.String(length=16), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('cnp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('marital_status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('medical_record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_patient_serie_buletin')
        batch_op.create_index(batch_op.f('ix_patient_id_number'), ['id_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_id_series'), ['id_series'], unique=True)
        batch_op.drop_column('serie_buletin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie_buletin', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_index(batch_op.f('ix_patient_id_series'))
        batch_op.drop_index(batch_op.f('ix_patient_id_number'))
        batch_op.create_index('ix_patient_serie_buletin', ['serie_buletin'], unique=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('medical_record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('marital_status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('cnp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('id_number')
        batch_op.drop_column('id_series')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('consultation_schedule_away',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('consultation_schedule_office',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('consultation', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
